# model
num_joints: 21
num_classes: 12
classifier_name: "poseresnet_large_with_aug_best"
detector_name: "SSDLite"

# data
data_path: "data/test.mov"
save_path: "result.mov"

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  like: 3
  mute: 4
  ok: 5
  one: 6
  palm: 7
  peace: 8
  peace_inverted: 9
  stop: 10
  stop_inverted: 11

img_size_for_detection: 320
img_size_for_classification: 256

# result
display: True
