# model
num_joints: 21
num_classes: 12
model_name: "poseresnet"

# dataset
data_path: "data/hagrid/train"

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  like: 3
  mute: 4
  ok: 5
  one: 6
  palm: 7
  peace: 8
  peace_inverted: 9
  stop: 10
  stop_inverted: 11

batch_size: 32
img_size: 256
sigma: 3

# data preprocess and augmentation
preprocess:
  crop_FOA: True
  resize_FOA: True
  rotate: False
  horizontal_flip: False
  hsv: False

# hyperparameters
epochs: 20
learning_rate: 0.001
